--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Mar 09 2015 19:07
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'F15I4PRJ4Gr3'
--
USE F15I4PRJ4Gr3
GO
 
IF DB_NAME() = 'F15I4PRJ4Gr3'
    RAISERROR('''F15I4PRJ4Gr3'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE F15I4PRJ4Gr3'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
EXECUTE SP_DBOPTION 'F15I4PRJ4Gr3' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO

--
-- Create Table    : 'Quiz'   
-- QuizId          :  
-- QuizName        :  
--
CREATE TABLE Quiz (
    QuizId         INT NOT NULL UNIQUE,
    QuizName       NVARCHAR(75) NOT NULL,
CONSTRAINT pk_Quiz PRIMARY KEY CLUSTERED (QuizId))
GO

--
-- Create Table    : 'Tags'   
-- TagId           :  
-- Tag             :  
--
CREATE TABLE Tags (
    TagId          INT NOT NULL UNIQUE,
    Tag            NVARCHAR(75) NOT NULL UNIQUE,
CONSTRAINT pk_Tags PRIMARY KEY CLUSTERED (TagId))
GO

--
-- Create Table    : 'Questions'   
-- QuestionId      :  
-- Question        :  
-- QuizId          :  (references Quiz.QuizId)
--
CREATE TABLE Questions (
    QuestionId     INT NOT NULL UNIQUE,
    Question       NVARCHAR(75) NOT NULL,
    QuizId         INT NOT NULL,
CONSTRAINT pk_Questions PRIMARY KEY CLUSTERED (QuestionId),
CONSTRAINT fk_Questions FOREIGN KEY (QuizId)
    REFERENCES Quiz (QuizId)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Answers'   
-- AnswerId        :  
-- Answer          :  
-- Correct         :  
-- QuestionId      :  (references Questions.QuestionId)
--
CREATE TABLE Answers (
    AnswerId       INT NOT NULL UNIQUE,
    Answer         NVARCHAR(75) NOT NULL,
    Correct        CHAR(1) NOT NULL,
    QuestionId     INT NOT NULL,
CONSTRAINT pk_Answers PRIMARY KEY CLUSTERED (AnswerId),
CONSTRAINT fk_Answers FOREIGN KEY (QuestionId)
    REFERENCES Questions (QuestionId)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'QuizTagRelation'   
-- QuizId          :  (references Quiz.QuizId)
-- TagId           :  (references Tags.TagId)
--
CREATE TABLE QuizTagRelation (
    QuizId         INT NOT NULL,
    TagId          INT NOT NULL,
CONSTRAINT pk_QuizTagRelation PRIMARY KEY CLUSTERED (QuizId,TagId),
CONSTRAINT fk_QuizTagRelation FOREIGN KEY (QuizId)
    REFERENCES Quiz (QuizId)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_QuizTagRelation2 FOREIGN KEY (TagId)
    REFERENCES Tags (TagId)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Quiz TO public
GO
GRANT ALL ON Tags TO public
GO
GRANT ALL ON Questions TO public
GO
GRANT ALL ON Answers TO public
GO
GRANT ALL ON QuizTagRelation TO public
GO

