//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Answer
	{
		public virtual string Text
		{
			get;
			set;
		}

		public virtual bool Correct
		{
			get;
			set;
		}

		public virtual int AnswerId
		{
			get;
			set;
		}

		public virtual object QuestionId
		{
			get;
			set;
		}

	}
}

