//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Question
	{
		public virtual string Text
		{
			get;
			set;
		}

		public virtual int QuestionId
		{
			get;
			set;
		}

		public virtual Quiz Quiz
		{
			get;
			set;
		}

	}
}

