//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Quiz
	{
		public virtual string QuizName
		{
			get;
			set;
		}

		public virtual int QuizId
		{
			get;
			set;
		}

		public virtual IEnumerable<Question> Question
		{
			get;
			set;
		}

		public virtual IEnumerable<QuizTagRelation> QuizTagRelation
		{
			get;
			set;
		}

	}
}

