var hierarchy =
[
    [ "Website.Models.Answer", "class_website_1_1_models_1_1_answer.html", null ],
    [ "Website.Models.AnswerQuizLog", "class_website_1_1_models_1_1_answer_quiz_log.html", null ],
    [ "ApiController", null, [
      [ "Website.Controllers.LoginController", "class_website_1_1_controllers_1_1_login_controller.html", null ]
    ] ],
    [ "Website.AspNetRoles", "class_website_1_1_asp_net_roles.html", null ],
    [ "Website.AspNetUserClaims", "class_website_1_1_asp_net_user_claims.html", null ],
    [ "Website.AspNetUserLogins", "class_website_1_1_asp_net_user_logins.html", null ],
    [ "Website.AspNetUsers", "class_website_1_1_asp_net_users.html", null ],
    [ "Website.Models.AspNetUsersViewModel", "class_website_1_1_models_1_1_asp_net_users_view_model.html", null ],
    [ "Website.BundleConfig", "class_website_1_1_bundle_config.html", null ],
    [ "Website.Models.ConfigGroupViewModel", "class_website_1_1_models_1_1_config_group_view_model.html", null ],
    [ "Controller", null, [
      [ "Website.Controllers.AnswerQuizController", "class_website_1_1_controllers_1_1_answer_quiz_controller.html", null ],
      [ "Website.Controllers.ConfigGroupController", "class_website_1_1_controllers_1_1_config_group_controller.html", null ],
      [ "Website.Controllers.ConfigQuizzesController", "class_website_1_1_controllers_1_1_config_quizzes_controller.html", null ],
      [ "Website.Controllers.ConfigUserController", "class_website_1_1_controllers_1_1_config_user_controller.html", null ],
      [ "Website.Controllers.CreateQuizController", "class_website_1_1_controllers_1_1_create_quiz_controller.html", null ],
      [ "Website.Controllers.CreateUserController", "class_website_1_1_controllers_1_1_create_user_controller.html", null ],
      [ "Website.Controllers.FacebookRegisterController", "class_website_1_1_controllers_1_1_facebook_register_controller.html", null ],
      [ "Website.Controllers.FavoritesController", "class_website_1_1_controllers_1_1_favorites_controller.html", null ],
      [ "Website.Controllers.FindQuizController", "class_website_1_1_controllers_1_1_find_quiz_controller.html", null ],
      [ "Website.Controllers.GroupController", "class_website_1_1_controllers_1_1_group_controller.html", null ],
      [ "Website.Controllers.HomeController", "class_website_1_1_controllers_1_1_home_controller.html", null ],
      [ "Website.Controllers.ValidationController", "class_website_1_1_controllers_1_1_validation_controller.html", null ]
    ] ],
    [ "DbContext", null, [
      [ "Website.Models.QuizCreatorContext", "class_website_1_1_models_1_1_quiz_creator_context.html", null ]
    ] ],
    [ "DbMigration", null, [
      [ "Website.Migrations.addquiz", "class_website_1_1_migrations_1_1addquiz.html", null ],
      [ "Website.Migrations.addquiz1", "class_website_1_1_migrations_1_1addquiz1.html", null ],
      [ "Website.Migrations.Anotherchangeagain", "class_website_1_1_migrations_1_1_anotherchangeagain.html", null ],
      [ "Website.Migrations.InitialMigrations", "class_website_1_1_migrations_1_1_initial_migrations.html", null ],
      [ "Website.Migrations.NotMappedDeleteQuestionAndAnswer", "class_website_1_1_migrations_1_1_not_mapped_delete_question_and_answer.html", null ],
      [ "Website.Migrations.nytQuestion", "class_website_1_1_migrations_1_1nyt_question.html", null ],
      [ "Website.Migrations.nytQuestion1", "class_website_1_1_migrations_1_1nyt_question1.html", null ],
      [ "Website.Migrations.nytQuestion2", "class_website_1_1_migrations_1_1nyt_question2.html", null ],
      [ "Website.Migrations.nytQuestion3", "class_website_1_1_migrations_1_1nyt_question3.html", null ],
      [ "Website.Migrations.nytQuestion4", "class_website_1_1_migrations_1_1nyt_question4.html", null ],
      [ "Website.Migrations.nytQuestion5", "class_website_1_1_migrations_1_1nyt_question5.html", null ],
      [ "Website.Migrations.nytQuestion6", "class_website_1_1_migrations_1_1nyt_question6.html", null ],
      [ "Website.Migrations.questionadd", "class_website_1_1_migrations_1_1questionadd.html", null ],
      [ "Website.Migrations.questionadd1", "class_website_1_1_migrations_1_1questionadd1.html", null ],
      [ "Website.Migrations.questionadd2", "class_website_1_1_migrations_1_1questionadd2.html", null ],
      [ "Website.Migrations.questionadd3", "class_website_1_1_migrations_1_1questionadd3.html", null ],
      [ "Website.Migrations.questionadd4", "class_website_1_1_migrations_1_1questionadd4.html", null ],
      [ "Website.Migrations.questionadd5", "class_website_1_1_migrations_1_1questionadd5.html", null ],
      [ "Website.Migrations.SomeChangeIdid", "class_website_1_1_migrations_1_1_some_change_idid.html", null ],
      [ "Website.Migrations.test", "class_website_1_1_migrations_1_1test.html", null ],
      [ "Website.Migrations.test", "class_website_1_1_migrations_1_1test.html", null ],
      [ "Website.Migrations.x", "class_website_1_1_migrations_1_1x.html", null ],
      [ "Website.Migrations.x1", "class_website_1_1_migrations_1_1x1.html", null ],
      [ "Website.Migrations.x10", "class_website_1_1_migrations_1_1x10.html", null ],
      [ "Website.Migrations.x11", "class_website_1_1_migrations_1_1x11.html", null ],
      [ "Website.Migrations.x12", "class_website_1_1_migrations_1_1x12.html", null ],
      [ "Website.Migrations.x13", "class_website_1_1_migrations_1_1x13.html", null ],
      [ "Website.Migrations.x14", "class_website_1_1_migrations_1_1x14.html", null ],
      [ "Website.Migrations.x15", "class_website_1_1_migrations_1_1x15.html", null ],
      [ "Website.Migrations.x16", "class_website_1_1_migrations_1_1x16.html", null ],
      [ "Website.Migrations.x17", "class_website_1_1_migrations_1_1x17.html", null ],
      [ "Website.Migrations.x18", "class_website_1_1_migrations_1_1x18.html", null ],
      [ "Website.Migrations.x19", "class_website_1_1_migrations_1_1x19.html", null ],
      [ "Website.Migrations.x2", "class_website_1_1_migrations_1_1x2.html", null ],
      [ "Website.Migrations.x20", "class_website_1_1_migrations_1_1x20.html", null ],
      [ "Website.Migrations.x21", "class_website_1_1_migrations_1_1x21.html", null ],
      [ "Website.Migrations.x22", "class_website_1_1_migrations_1_1x22.html", null ],
      [ "Website.Migrations.x23", "class_website_1_1_migrations_1_1x23.html", null ],
      [ "Website.Migrations.x24", "class_website_1_1_migrations_1_1x24.html", null ],
      [ "Website.Migrations.x25", "class_website_1_1_migrations_1_1x25.html", null ],
      [ "Website.Migrations.x26", "class_website_1_1_migrations_1_1x26.html", null ],
      [ "Website.Migrations.x27", "class_website_1_1_migrations_1_1x27.html", null ],
      [ "Website.Migrations.x28", "class_website_1_1_migrations_1_1x28.html", null ],
      [ "Website.Migrations.x29", "class_website_1_1_migrations_1_1x29.html", null ],
      [ "Website.Migrations.x3", "class_website_1_1_migrations_1_1x3.html", null ],
      [ "Website.Migrations.x30", "class_website_1_1_migrations_1_1x30.html", null ],
      [ "Website.Migrations.x31", "class_website_1_1_migrations_1_1x31.html", null ],
      [ "Website.Migrations.x32", "class_website_1_1_migrations_1_1x32.html", null ],
      [ "Website.Migrations.x33", "class_website_1_1_migrations_1_1x33.html", null ],
      [ "Website.Migrations.x34", "class_website_1_1_migrations_1_1x34.html", null ],
      [ "Website.Migrations.x35", "class_website_1_1_migrations_1_1x35.html", null ],
      [ "Website.Migrations.x4", "class_website_1_1_migrations_1_1x4.html", null ],
      [ "Website.Migrations.x5", "class_website_1_1_migrations_1_1x5.html", null ],
      [ "Website.Migrations.x6", "class_website_1_1_migrations_1_1x6.html", null ],
      [ "Website.Migrations.x7", "class_website_1_1_migrations_1_1x7.html", null ],
      [ "Website.Migrations.x8", "class_website_1_1_migrations_1_1x8.html", null ],
      [ "Website.Migrations.x9", "class_website_1_1_migrations_1_1x9.html", null ]
    ] ],
    [ "Exception", null, [
      [ "Website.Models.NoAnswerFoundException", "class_website_1_1_models_1_1_no_answer_found_exception.html", null ],
      [ "Website.Models.NoAnswersFoundException", "class_website_1_1_models_1_1_no_answers_found_exception.html", null ],
      [ "Website.Models.NoQuestionFoundException", "class_website_1_1_models_1_1_no_question_found_exception.html", null ],
      [ "Website.Models.UserRightsException", "class_website_1_1_models_1_1_user_rights_exception.html", null ]
    ] ],
    [ "Website.Models.FavoriteGroup", "class_website_1_1_models_1_1_favorite_group.html", null ],
    [ "Website.Models.FavoriteQuiz", "class_website_1_1_models_1_1_favorite_quiz.html", null ],
    [ "Website.FilterConfig", "class_website_1_1_filter_config.html", null ],
    [ "Website.Models.Group", "class_website_1_1_models_1_1_group.html", null ],
    [ "HttpApplication", null, [
      [ "Website.MvcApplication", "class_website_1_1_mvc_application.html", null ]
    ] ],
    [ "Website.Models.IDALEF", "interface_website_1_1_models_1_1_i_d_a_l_e_f.html", [
      [ "Website.Models.DALEF", "class_website_1_1_models_1_1_d_a_l_e_f.html", null ]
    ] ],
    [ "Website.Models.IFile", "interface_website_1_1_models_1_1_i_file.html", [
      [ "Website.Models.SystemIoFile", "class_website_1_1_models_1_1_system_io_file.html", null ]
    ] ],
    [ "IMigrationMetadata", null, [
      [ "Website.Migrations.addquiz", "class_website_1_1_migrations_1_1addquiz.html", null ],
      [ "Website.Migrations.addquiz1", "class_website_1_1_migrations_1_1addquiz1.html", null ],
      [ "Website.Migrations.Anotherchangeagain", "class_website_1_1_migrations_1_1_anotherchangeagain.html", null ],
      [ "Website.Migrations.InitialMigrations", "class_website_1_1_migrations_1_1_initial_migrations.html", null ],
      [ "Website.Migrations.NotMappedDeleteQuestionAndAnswer", "class_website_1_1_migrations_1_1_not_mapped_delete_question_and_answer.html", null ],
      [ "Website.Migrations.nytQuestion", "class_website_1_1_migrations_1_1nyt_question.html", null ],
      [ "Website.Migrations.nytQuestion1", "class_website_1_1_migrations_1_1nyt_question1.html", null ],
      [ "Website.Migrations.nytQuestion2", "class_website_1_1_migrations_1_1nyt_question2.html", null ],
      [ "Website.Migrations.nytQuestion3", "class_website_1_1_migrations_1_1nyt_question3.html", null ],
      [ "Website.Migrations.nytQuestion4", "class_website_1_1_migrations_1_1nyt_question4.html", null ],
      [ "Website.Migrations.nytQuestion5", "class_website_1_1_migrations_1_1nyt_question5.html", null ],
      [ "Website.Migrations.nytQuestion6", "class_website_1_1_migrations_1_1nyt_question6.html", null ],
      [ "Website.Migrations.questionadd", "class_website_1_1_migrations_1_1questionadd.html", null ],
      [ "Website.Migrations.questionadd1", "class_website_1_1_migrations_1_1questionadd1.html", null ],
      [ "Website.Migrations.questionadd2", "class_website_1_1_migrations_1_1questionadd2.html", null ],
      [ "Website.Migrations.questionadd3", "class_website_1_1_migrations_1_1questionadd3.html", null ],
      [ "Website.Migrations.questionadd4", "class_website_1_1_migrations_1_1questionadd4.html", null ],
      [ "Website.Migrations.questionadd5", "class_website_1_1_migrations_1_1questionadd5.html", null ],
      [ "Website.Migrations.SomeChangeIdid", "class_website_1_1_migrations_1_1_some_change_idid.html", null ],
      [ "Website.Migrations.test", "class_website_1_1_migrations_1_1test.html", null ],
      [ "Website.Migrations.x", "class_website_1_1_migrations_1_1x.html", null ],
      [ "Website.Migrations.x1", "class_website_1_1_migrations_1_1x1.html", null ],
      [ "Website.Migrations.x10", "class_website_1_1_migrations_1_1x10.html", null ],
      [ "Website.Migrations.x11", "class_website_1_1_migrations_1_1x11.html", null ],
      [ "Website.Migrations.x12", "class_website_1_1_migrations_1_1x12.html", null ],
      [ "Website.Migrations.x13", "class_website_1_1_migrations_1_1x13.html", null ],
      [ "Website.Migrations.x14", "class_website_1_1_migrations_1_1x14.html", null ],
      [ "Website.Migrations.x15", "class_website_1_1_migrations_1_1x15.html", null ],
      [ "Website.Migrations.x16", "class_website_1_1_migrations_1_1x16.html", null ],
      [ "Website.Migrations.x17", "class_website_1_1_migrations_1_1x17.html", null ],
      [ "Website.Migrations.x18", "class_website_1_1_migrations_1_1x18.html", null ],
      [ "Website.Migrations.x19", "class_website_1_1_migrations_1_1x19.html", null ],
      [ "Website.Migrations.x2", "class_website_1_1_migrations_1_1x2.html", null ],
      [ "Website.Migrations.x20", "class_website_1_1_migrations_1_1x20.html", null ],
      [ "Website.Migrations.x21", "class_website_1_1_migrations_1_1x21.html", null ],
      [ "Website.Migrations.x22", "class_website_1_1_migrations_1_1x22.html", null ],
      [ "Website.Migrations.x23", "class_website_1_1_migrations_1_1x23.html", null ],
      [ "Website.Migrations.x24", "class_website_1_1_migrations_1_1x24.html", null ],
      [ "Website.Migrations.x25", "class_website_1_1_migrations_1_1x25.html", null ],
      [ "Website.Migrations.x26", "class_website_1_1_migrations_1_1x26.html", null ],
      [ "Website.Migrations.x27", "class_website_1_1_migrations_1_1x27.html", null ],
      [ "Website.Migrations.x28", "class_website_1_1_migrations_1_1x28.html", null ],
      [ "Website.Migrations.x29", "class_website_1_1_migrations_1_1x29.html", null ],
      [ "Website.Migrations.x3", "class_website_1_1_migrations_1_1x3.html", null ],
      [ "Website.Migrations.x30", "class_website_1_1_migrations_1_1x30.html", null ],
      [ "Website.Migrations.x31", "class_website_1_1_migrations_1_1x31.html", null ],
      [ "Website.Migrations.x32", "class_website_1_1_migrations_1_1x32.html", null ],
      [ "Website.Migrations.x33", "class_website_1_1_migrations_1_1x33.html", null ],
      [ "Website.Migrations.x34", "class_website_1_1_migrations_1_1x34.html", null ],
      [ "Website.Migrations.x35", "class_website_1_1_migrations_1_1x35.html", null ],
      [ "Website.Migrations.x4", "class_website_1_1_migrations_1_1x4.html", null ],
      [ "Website.Migrations.x5", "class_website_1_1_migrations_1_1x5.html", null ],
      [ "Website.Migrations.x6", "class_website_1_1_migrations_1_1x6.html", null ],
      [ "Website.Migrations.x7", "class_website_1_1_migrations_1_1x7.html", null ],
      [ "Website.Migrations.x8", "class_website_1_1_migrations_1_1x8.html", null ],
      [ "Website.Migrations.x9", "class_website_1_1_migrations_1_1x9.html", null ]
    ] ],
    [ "Website.Controllers.IQuizModel", "interface_website_1_1_controllers_1_1_i_quiz_model.html", [
      [ "Website.Models.QuizModel", "class_website_1_1_models_1_1_quiz_model.html", null ]
    ] ],
    [ "Website.Models.Question", "class_website_1_1_models_1_1_question.html", null ],
    [ "Website.Models.Quiz", "class_website_1_1_models_1_1_quiz.html", null ],
    [ "Website.Models.QuizViewModel", "class_website_1_1_models_1_1_quiz_view_model.html", null ],
    [ "Website.RouteConfig", "class_website_1_1_route_config.html", null ],
    [ "Website.Startup", "class_website_1_1_startup.html", null ],
    [ "Website.Models.Tag", "class_website_1_1_models_1_1_tag.html", null ],
    [ "Website.Controllers.tempUser", "class_website_1_1_controllers_1_1temp_user.html", null ]
];