//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace QuizCreator
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Answers
	{
		public virtual string Answer
		{
			get;
			set;
		}

		public virtual bool Correct
		{
			get;
			set;
		}

		public virtual int AnswerId
		{
			get;
			set;
		}

	}
}

