
--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Mar 09 2015 19:07
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'F15I4PRJ4Gr3'
--
USE F15I4PRJ4Gr3
GO

IF DB_NAME() = 'F15I4PRJ4Gr3'
    RAISERROR('''F15I4PRJ4Gr3'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE F15I4PRJ4Gr3'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
GO

EXECUTE SP_DBOPTION 'F15I4PRJ4Gr3' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Quiz TO public
GO

GRANT ALL ON Tags TO public
GO

GRANT ALL ON Questions TO public
GO

GRANT ALL ON Answers TO public
GO

GRANT ALL ON QuizTagRelation TO public
GO
